# ============================================
# Grafana Datasources Configuration
# ============================================

apiVersion: 1

datasources:
  # =====================================
  # Prometheus - Metrics
  # =====================================
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: loki

  # =====================================
  # Loki - Logs
  # =====================================
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # =====================================
  # Node Exporter Dashboard Support
  # =====================================
  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: node-exporter
    editable: true
    jsonData:
      timeInterval: 30s
      httpMethod: POST